[en]
contentDir = "content/english"
copyright = ""
footer_content = "info@eccoastal.com"
footer_menu_left = ""
footer_menu_middle = ""
footer_menu_right = ""
languageName = "En"
title = "EC Coastal"
weight = 1
