footer_left = []
footer_middle = []
footer_right = []
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Services"
url = "#blog"
weight = 2
[[main]]
name = "About Us"
url = "#about us"
weight = 5
